# Generated by Django 4.0.4 on 2023-08-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
